# Generated by Django 5.0.2 on 2024-02-18 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base64_uploads', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fileupload',
            name='document',
        ),
        migrations.AddField(
            model_name='fileupload',
            name='doc',
            field=models.FileField(default='not available', upload_to='docs/'),
            preserve_default=False,
        ),
    ]
