# Generated by Django 5.0.2 on 2024-02-19 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('associated_keyword', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='FileWithKeywords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword_doc', models.FileField(upload_to='keyword_docs/')),
                ('keyword', models.ManyToManyField(to='keywords.keyword')),
            ],
        ),
    ]
